site_name: AdvogaAI
theme:
  #name: dracula
  name: material
nav:
  - Início: inicio.md
  - Visão de Produto e Projeto: 
      -  Cenário Atual do Cliente e do Negócio: produto.md
      - Solução Proposta: solucao.md
      - Requisitos Funcionais e Não-Funcionais: requisitos.md
      - Estratégias de Engenharia de Software: estrategia.md
      - Cronograma: cronograma.md
      - Interação entre Equipe e Cliente: equipecliente.md
  - Entregas:
      - Unidade 1: unidade1.md
  - Nomeclaturas: naming.md
