site_name: AdvogaAI
theme:
  #name: dracula
  name: material
nav:
  - Vis√£o de produto: produto.md
  - Atas:
      - ata-modelo: Atas/ata-modelo.md

  - Sprints:
      - Sprint 0: Sprints/sprint0.md
