site_name: AdvogaAI
theme:
  #name: dracula
  name: material
nav:
  - Início: inicio.md
  - Visão de Produto e Projeto: 
      -  Cenário Atual do Cliente e do Negócio: produto.md
      - Solução Proposta: solucao.md
      - Estratégias de Engenharia de Software: estrategia.md
      - Cronograma: cronograma.md
      - Interação entre Equipe e Cliente: equipecliente.md
  - Atas:
      - ata-modelo: Atas/ata-modelo.md

  - Sprints:
      - Sprint 0: Sprints/sprint0.md
